BEGIN TRY

BEGIN TRAN;

-- AlterTable
ALTER TABLE [dbo].[M200_Office] ALTER COLUMN [CreateDateTime] DATETIME NULL;
ALTER TABLE [dbo].[M200_Office] ALTER COLUMN [CreateUserId] VARCHAR(10) NULL;
ALTER TABLE [dbo].[M200_Office] ALTER COLUMN [UpdateDateTime] DATETIME NULL;
ALTER TABLE [dbo].[M200_Office] ALTER COLUMN [UpdateUserId] VARCHAR(10) NULL;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
